# Generated by Django 4.1.2 on 2022-12-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_remove_addition_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='rating',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='jokes.rating', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
