# Generated by Django 4.1.2 on 2022-12-11 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jokes', '0004_alter_addition_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='marked_by_users',
            field=models.ManyToManyField(related_name='marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
